"""Application constants"""

# User Roles
ROLE_ADMIN = "admin"
ROLE_USER = "user"

VALID_ROLES = [ROLE_ADMIN, ROLE_USER]

# Log Sources
LOG_SOURCE_PRTG = "prtg"
LOG_SOURCE_ELASTIC = "elastic"
LOG_SOURCE_SYSTEM = "system"

VALID_LOG_SOURCES = [LOG_SOURCE_PRTG, LOG_SOURCE_ELASTIC, LOG_SOURCE_SYSTEM]

# Log Severity Levels
SEVERITY_INFO = "info"
SEVERITY_WARNING = "warning"
SEVERITY_CRITICAL = "critical"

VALID_SEVERITY_LEVELS = [SEVERITY_INFO, SEVERITY_WARNING, SEVERITY_CRITICAL]

# Alert Status
ALERT_STATUS_NEW = "new"
ALERT_STATUS_ACK = "ack"
ALERT_STATUS_RESOLVED = "resolved"

VALID_ALERT_STATUS = [ALERT_STATUS_NEW, ALERT_STATUS_ACK, ALERT_STATUS_RESOLVED]
